birth = int(input("What year were you born fellow person? - "))
montyh = str(input("What month was this year?"))
  if month.lower = "january"
    birth = 1
  elif month.lower = "febuary"
    birth = 2
  elif month.lower = "march"
    birth = 3
  elif month.lower = "april"
    birth = 4
  elif month.lower = "may"
    birth = 5
  elif month.lower = "june"
    birth = 6
  elif month.lower = "july"
    birth = 7
  elif month.lower = "august"
    birth = 8